---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: generated-s3-password
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "my-app-s3-credentials"
spec:
  refreshInterval: "30m0s"
  target:
    name: my-app-s3-credentials
    #creationPolicy: 'Merge'
    template:
      metadata:
        annotations:
          s3-resource-operator.io/enabled: "true"
      data:
        bucket-name: "my-app-backups"
        access-key: "myapp"
        secret-key: "{{ .password }}"
        endpoint-url: "http://versitygw.versitygw.svc.cluster.local:7070"
        role: "user"
        user-id: "1001"
        group-id: "1001"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "generated-s3-password"
~
